# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
make_eleves
make_profs
make_instruments

def make_eleves
	Eleve.create(:nom => 'ABEILLE', :prenom => 'Maximilien')
	Eleve.create(:nom => 'ABEILLE', :prenom => 'Bastien')
	Eleve.create(:nom => 'AGULLO', :prenom => 'Tristan')
	Eleve.create(:nom => 'ANTOINE', :prenom => 'Jean-francois')
	Eleve.create(:nom => 'BALES', :prenom => 'Noa')
	Eleve.create(:nom => 'BEAUD', :prenom => 'Matilde')
	Eleve.create(:nom => 'BEAULIEUX', :prenom => 'Angeline')
	Eleve.create(:nom => 'BEAUMEL', :prenom => 'Capucine')
	Eleve.create(:nom => 'BEDAU', :prenom => 'Anna')
	Eleve.create(:nom => 'BERARD', :prenom => 'Nina')
	Eleve.create(:nom => 'BERNIER', :prenom => 'Sarah')
	Eleve.create(:nom => 'BERTRAM', :prenom => 'Timothee')
	Eleve.create(:nom => 'BLAISSE', :prenom => 'Capucine')
	Eleve.create(:nom => 'BOCOZ', :prenom => 'Adrien')
	Eleve.create(:nom => 'BONNAFY-DEROYS', :prenom => 'Romane')
	Eleve.create(:nom => 'BONNAFY-DEROYS', :prenom => 'Mathilde')
	Eleve.create(:nom => 'BOULINGES', :prenom => 'Loan')
	Eleve.create(:nom => 'BOURDENX', :prenom => 'Marine')
	Eleve.create(:nom => 'BOURDENX', :prenom => 'Maelys')
	Eleve.create(:nom => 'BOURDON', :prenom => 'Alexis')
	Eleve.create(:nom => 'BOURDON', :prenom => 'Maelle')
	Eleve.create(:nom => 'BOUTIN', :prenom => 'Romain')
	Eleve.create(:nom => 'BROYELLE', :prenom => 'Mika')
	Eleve.create(:nom => 'CABRERA', :prenom => 'Alexia')
	Eleve.create(:nom => 'CANONNE', :prenom => 'Gorann')
	Eleve.create(:nom => 'CANONNE', :prenom => 'Anouk')
	Eleve.create(:nom => 'CANONNE', :prenom => 'Eva')
	Eleve.create(:nom => 'CARDONA-CEPPE', :prenom => 'Heloise')
	Eleve.create(:nom => 'CAZOTTES', :prenom => 'Paul')
	Eleve.create(:nom => 'CHAIA', :prenom => 'Eric')
	Eleve.create(:nom => 'CHALNOT', :prenom => 'Eliott')
	Eleve.create(:nom => 'CHAMAND', :prenom => 'Yanis')
	Eleve.create(:nom => 'CHAUMEIL', :prenom => 'Remi')
	Eleve.create(:nom => 'CHELIOUT', :prenom => 'Clara')
	Eleve.create(:nom => 'CHEVY', :prenom => 'Pierre')
	Eleve.create(:nom => 'CHOLLET', :prenom => 'Remy')
	Eleve.create(:nom => 'COTTET', :prenom => 'Anna')
	Eleve.create(:nom => 'COUDERC', :prenom => 'Christophe')
	Eleve.create(:nom => 'COULIBALY', :prenom => 'Esther')
	Eleve.create(:nom => 'COULIBALY', :prenom => 'Mathys')
	Eleve.create(:nom => 'CRETIN', :prenom => 'Juliette')
	Eleve.create(:nom => 'CURVALLE', :prenom => 'Karine')
	Eleve.create(:nom => 'DARAUT-ROLDAN', :prenom => 'Sarah')
	Eleve.create(:nom => 'DARNATIGUES', :prenom => 'Guillaume')
	Eleve.create(:nom => 'DAUSSAN', :prenom => 'Fabrice')
	Eleve.create(:nom => 'DEBAERE-LAFONT', :prenom => 'Timote')
	Eleve.create(:nom => 'DEBAERE-LAFONT', :prenom => 'Emilien')
	Eleve.create(:nom => 'DECURE', :prenom => 'Alexandre')
	Eleve.create(:nom => 'DEMAISON', :prenom => 'Myriam')
	Eleve.create(:nom => 'DEVIER', :prenom => 'Dominique')
	Eleve.create(:nom => 'DIEZ', :prenom => 'Emma')
	Eleve.create(:nom => 'DIEZ', :prenom => 'Lucas')
	Eleve.create(:nom => 'FERRINI', :prenom => 'Lola')
	Eleve.create(:nom => 'FORTUNATO', :prenom => 'Guillaume')
	Eleve.create(:nom => 'GALLAND', :prenom => 'Marie-Amelie')
	Eleve.create(:nom => 'GALZIN', :prenom => 'Sophie')
	Eleve.create(:nom => 'GARCIA', :prenom => 'Lena')
	Eleve.create(:nom => 'GIORIA', :prenom => 'Pauline')
	Eleve.create(:nom => 'GOURDEAS', :prenom => 'Brice')
	Eleve.create(:nom => 'GRANDJEAN', :prenom => 'Margot')
	Eleve.create(:nom => 'GROUSSET', :prenom => 'Celine')
	Eleve.create(:nom => 'GROUSSET', :prenom => 'Jer™me')
	Eleve.create(:nom => 'GROUZIS', :prenom => 'Christophe')
	Eleve.create(:nom => 'HERSEN', :prenom => 'Paul-Emile')
	Eleve.create(:nom => 'IACAZIO', :prenom => 'Mathis')
	Eleve.create(:nom => 'IACAZIO', :prenom => 'Elena')
	Eleve.create(:nom => 'IZIC', :prenom => 'Emilien')
	Eleve.create(:nom => 'JAEGER', :prenom => 'Titouan')
	Eleve.create(:nom => 'JEROME', :prenom => 'Lucette')
	Eleve.create(:nom => 'JULIAN', :prenom => 'Kim')
	Eleve.create(:nom => 'JULIEN', :prenom => 'Leos')
	Eleve.create(:nom => 'KAESTNER-LAFONT', :prenom => 'Amandine')
	Eleve.create(:nom => 'LALEQUE', :prenom => 'Guilhem')
	Eleve.create(:nom => 'LAMOUROUX', :prenom => 'Simon')
	Eleve.create(:nom => 'LAPINTE', :prenom => 'Garance')
	Eleve.create(:nom => 'LAROCHE', :prenom => 'Francis')
	Eleve.create(:nom => 'LAROCHE', :prenom => 'Nadine')
	Eleve.create(:nom => 'LAROCHE', :prenom => 'Simon')
	Eleve.create(:nom => 'LAROCHE', :prenom => 'Alexis')
	Eleve.create(:nom => 'LAROCHE', :prenom => 'Etienne')
	Eleve.create(:nom => 'LASSERE', :prenom => 'Pierre')
	Eleve.create(:nom => 'LASSERE', :prenom => 'Shahnez')
	Eleve.create(:nom => 'LEBON', :prenom => 'Eric')
	Eleve.create(:nom => 'LECLERCQ', :prenom => 'Tristan')
	Eleve.create(:nom => 'LECLERCQ', :prenom => 'Rebecca')
	Eleve.create(:nom => 'LEDOUX', :prenom => 'Aya')
	Eleve.create(:nom => 'LEMAISTRE', :prenom => 'Xavier')
	Eleve.create(:nom => 'LHUISSIER', :prenom => 'Mateo')
	Eleve.create(:nom => 'LIDON', :prenom => 'Fernand')
	Eleve.create(:nom => 'LOGEREAU', :prenom => 'Leana')
	Eleve.create(:nom => 'LOPES', :prenom => 'Clement')
	Eleve.create(:nom => 'LUCAS', :prenom => 'Ombeline')
	Eleve.create(:nom => 'MANZI', :prenom => 'Mathilde')
	Eleve.create(:nom => 'MARTEAU', :prenom => 'Patrice')
	Eleve.create(:nom => 'MARTIN', :prenom => 'Loic')
	Eleve.create(:nom => 'MARTINEZ', :prenom => 'Elsa')
	Eleve.create(:nom => 'MARTINEZ', :prenom => 'Maude')
	Eleve.create(:nom => 'MASSE', :prenom => 'Melanie')
	Eleve.create(:nom => 'MASY', :prenom => 'Louise')
	Eleve.create(:nom => 'MAULANDI', :prenom => 'Franck')
	Eleve.create(:nom => 'MEGE', :prenom => 'Annie')
	Eleve.create(:nom => 'MERMIER', :prenom => 'Charlotte')
	Eleve.create(:nom => 'MICHEL', :prenom => 'Melodie')
	Eleve.create(:nom => 'MICHUN', :prenom => 'Clemence')
	Eleve.create(:nom => 'MIKLIK', :prenom => 'Yoan')
	Eleve.create(:nom => 'MIKLIK', :prenom => 'Priscilia')
	Eleve.create(:nom => 'MONTEZCA-VALLESPIN', :prenom => 'Dorian')
	Eleve.create(:nom => 'MOREAU', :prenom => 'Paul')
	Eleve.create(:nom => 'MOURAUX', :prenom => 'Eliot')
	Eleve.create(:nom => 'MUZELLEC', :prenom => 'Basil')
	Eleve.create(:nom => 'NAVES', :prenom => 'Eric')
	Eleve.create(:nom => 'NICOL', :prenom => 'Fabien')
	Eleve.create(:nom => 'PASTRE', :prenom => 'Lilas')
	Eleve.create(:nom => 'PEREZ', :prenom => 'Alice')
	Eleve.create(:nom => 'PEREZ', :prenom => 'Claire')
	Eleve.create(:nom => 'PERICE', :prenom => 'Daniel')
	Eleve.create(:nom => 'PERISSE', :prenom => 'Ins')
	Eleve.create(:nom => 'PHUNG', :prenom => 'Estelle')
	Eleve.create(:nom => 'PO', :prenom => 'Cathy')
	Eleve.create(:nom => 'POIRIER', :prenom => 'Marie')
	Eleve.create(:nom => 'POIRIER', :prenom => 'Genevive')
	Eleve.create(:nom => 'POLLINI', :prenom => 'Marie-Line')
	Eleve.create(:nom => 'POUDAVIGNE', :prenom => 'Victor')
	Eleve.create(:nom => 'POUDAVIGNE', :prenom => 'Theo')
	Eleve.create(:nom => 'POUDOU', :prenom => 'Adle')
	Eleve.create(:nom => 'PRIVAT', :prenom => 'Quentin')
	Eleve.create(:nom => 'PRIVAT', :prenom => 'Nathalie')
	Eleve.create(:nom => 'PRIVAT', :prenom => 'Sylvain')
	Eleve.create(:nom => 'RABAY', :prenom => 'Jacky')
	Eleve.create(:nom => 'RABINOWITZ', :prenom => 'Nina')
	Eleve.create(:nom => 'RICHARDOT', :prenom => 'Nina')
	Eleve.create(:nom => 'RIVAUD', :prenom => 'Julien')
	Eleve.create(:nom => 'ROBY', :prenom => 'Roxane')
	Eleve.create(:nom => 'ROBY', :prenom => 'Jessy')
	Eleve.create(:nom => 'ROUCOULES', :prenom => 'Thierry')
	Eleve.create(:nom => 'RUCHE', :prenom => 'Bianca')
	Eleve.create(:nom => 'SAINT-YVES', :prenom => 'Cyril')
	Eleve.create(:nom => 'SAINT-YVES', :prenom => 'Marc')
	Eleve.create(:nom => 'SELLES', :prenom => 'Cyprien')
	Eleve.create(:nom => 'SERAN', :prenom => 'Raphael')
	Eleve.create(:nom => 'SEYTE', :prenom => 'Auriane')
	Eleve.create(:nom => 'SPILMONT', :prenom => 'Juliette')
	Eleve.create(:nom => 'TASSERIT', :prenom => 'Mathieu')
	Eleve.create(:nom => 'TAVOILLOT', :prenom => 'Antoine')
	Eleve.create(:nom => 'TILLARD', :prenom => 'Pascal')
	Eleve.create(:nom => 'TRIVINO', :prenom => 'Guillem')
	Eleve.create(:nom => 'TUBAU', :prenom => 'Antoine')
	Eleve.create(:nom => 'VELJKOVIC', :prenom => 'Eva')
	Eleve.create(:nom => 'VITTORI', :prenom => 'Julien')
	Eleve.create(:nom => 'VITTORI', :prenom => 'Marc-Antoine')
end

def make_profs
	Professeur.create(:nom => 'Paz', :prenom => 'Fernando')
	Professeur.create(:nom => 'Tranchina', :prenom => 'Marie-Claude')
	Professeur.create(:nom => 'Chevalier', :prenom => 'Emmanuel')
	Professeur.create(:nom => 'Crocq', :prenom => 'Bastien')
	Professeur.create(:nom => 'Despringes', :prenom => 'Amalric')
	Professeur.create(:nom => 'Dulac', :prenom => 'Céline')
	Professeur.create(:nom => 'Espitalier', :prenom => 'Romain')
	Professeur.create(:nom => 'Gisclard', :prenom => 'Marie')
	Professeur.create(:nom => 'Limôge', :prenom => 'Yasuko')
	Professeur.create(:nom => 'Mégé', :prenom => 'Annie')
	Professeur.create(:nom => 'Rampaly', :prenom => 'Ralph')
	Professeur.create(:nom => 'Séverac', :prenom => 'Daniel')
	Professeur.create(:nom => 'Viollet', :prenom => 'Anne')
	Professeur.create(:nom => 'Cecillon', :prenom => 'Damien')
	Professeur.create(:nom => 'Sobas', :prenom => 'Maryline')
end

def make_instruments
	Instrument.create(:nom => 'Accordéon chromatique')
	Instrument.create(:nom => 'Accordéon diatonique')
	Instrument.create(:nom => 'Basse')
	Instrument.create(:nom => 'Batterie')
	Instrument.create(:nom => 'Chant')
	Instrument.create(:nom => 'Clarinette')
	Instrument.create(:nom => 'Flûte')
	Instrument.create(:nom => 'Guitare classique')
	Instrument.create(:nom => 'Guitare électrique')
	Instrument.create(:nom => 'Piano')
	Instrument.create(:nom => 'Saxophone')
	Instrument.create(:nom => 'Trombone')
	Instrument.create(:nom => 'Trompette')
	Instrument.create(:nom => 'Violon')
	Instrument.create(:nom => 'Violoncelle')
end
